backend:
  name: github
  repo: ssmith-wombatweb/simeonsmith.me
  squash_merges: true
  commit_messages:
    create: "Created {{collection}}: “{{slug}}”"
    update: "Updated {{collection}}: “{{slug}}”"
    delete: "Deleted {{collection}}: “{{slug}}”"
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”
publish_mode: editorial_workflow
media_folder: static/assets
public_folder: assets
site_url: https://www.simeonsmith.dev
logo_url: https://www.simeonsmith.dev/static/signature_large-9ce493b93708931522ea5edb1fe7bd33.png
collections:
  - name: blog
    label: Blog
    folder: src/articles/markdown
    slug: "{{date}}-{{slug}}"
    create: true
    fields:
      - { name: date, label: Date, widget: date, format: "YYYY-MM-DD", required: true  }
      - { name: title, label: Title, widget: string, required: true }
      - {
          label: "Repo",
          name: "repo",
          widget: "string",
          pattern: ["^(?:(?:(?:https?|ftp):)?\/\/)(?:\\S+(?::\\S*)?@)?(?:(?!(?:10|127)(?:\\.\\d{1,3}){3})(?!(?:169\\.254|192\\.168)(?:\\.\\d{1,3}){2})(?!172\\.(?:1[6-9]|2\\d|3[0-1])(?:\\.\\d{1,3}){2})(?:[1-9]\\d?|1\\d\\d|2[01]\\d|22[0-3])(?:\\.(?:1?\\d{1,2}|2[0-4]\\d|25[0-5])){2}(?:\\.(?:[1-9]\\d?|1\\d\\d|2[0-4]\\d|25[0-4]))|(?:(?:[a-z0-9\u00a1-\uffff][a-z0-9\u00a1-\uffff_-]{0,62})?[a-z0-9\u00a1-\uffff]\\.)+(?:[a-z\u00a1-\uffff]{2,}\\.?))(?::\\d{2,5})?(?:[/?#]\\S*)?$", "Must be a valid url"],
        }
      - {
          label: "Site",
          name: "site",
          widget: "string",
          pattern: ["^(?:(?:(?:https?|ftp):)?\/\/)(?:\\S+(?::\\S*)?@)?(?:(?!(?:10|127)(?:\\.\\d{1,3}){3})(?!(?:169\\.254|192\\.168)(?:\\.\\d{1,3}){2})(?!172\\.(?:1[6-9]|2\\d|3[0-1])(?:\\.\\d{1,3}){2})(?:[1-9]\\d?|1\\d\\d|2[01]\\d|22[0-3])(?:\\.(?:1?\\d{1,2}|2[0-4]\\d|25[0-5])){2}(?:\\.(?:[1-9]\\d?|1\\d\\d|2[0-4]\\d|25[0-4]))|(?:(?:[a-z0-9\u00a1-\uffff][a-z0-9\u00a1-\uffff_-]{0,62})?[a-z0-9\u00a1-\uffff]\\.)+(?:[a-z\u00a1-\uffff]{2,}\\.?))(?::\\d{2,5})?(?:[/?#]\\S*)?$", "Must be a valid url"],
        }
      - { name: body, label: Body, widget: markdown, required: true }